-- PostgreSQL baseline: the schema SQLite reaches after migrations 1-30
-- (server/migrations/001-030 plus the repairs in server/src/db.ts).
-- Generated from that schema, then reviewed. Type mapping:
--   TEXT    -> TEXT COLLATE "C"  (byte order, as SQLite's BINARY collation)
--   INTEGER -> BIGINT            (epoch-millisecond values exceed int4)
--   INTEGER -> DOUBLE PRECISION  for columns SQLite fills with fractional
--                                seconds: contributions.duration_seconds,
--                                cycles.seconds_used,
--                                contribution_quota_windows.seconds_used
--   REAL    -> DOUBLE PRECISION
--   AUTOINCREMENT -> GENERATED BY DEFAULT AS IDENTITY
-- Every foreign key is DEFERRABLE (initially immediate) so the one-off
-- SQLite import can load tables in any order inside one transaction.
-- A later schema change needs a SQLite migration and a matching file here
-- (server/migrations/postgres/NNN-*.sql); tests/postgres parity checks it.

CREATE TABLE schema_migrations (
  version BIGINT PRIMARY KEY,
  applied_at TEXT COLLATE "C" NOT NULL
);

-- PostgreSQL only: the environment (dev, release, ...) this database serves.
CREATE TABLE rewind_database_environment (
  singleton BOOLEAN PRIMARY KEY DEFAULT true CHECK (singleton),
  environment TEXT COLLATE "C" NOT NULL,
  bound_at TEXT COLLATE "C" NOT NULL
);

CREATE TABLE schema_migration_markers (
  migration_key TEXT COLLATE "C" PRIMARY KEY,
  applied_at TEXT COLLATE "C" NOT NULL
);

CREATE TABLE real_accounts (
  id TEXT COLLATE "C" PRIMARY KEY,
  username TEXT COLLATE "C" NOT NULL,
  normalized_username TEXT COLLATE "C" NOT NULL UNIQUE,
  display_name TEXT COLLATE "C" NOT NULL,
  password_salt TEXT COLLATE "C" NOT NULL UNIQUE,
  password_hash TEXT COLLATE "C" NOT NULL,
  password_scrypt_n BIGINT NOT NULL,
  password_scrypt_r BIGINT NOT NULL,
  password_scrypt_p BIGINT NOT NULL,
  created_at TEXT COLLATE "C" NOT NULL,
  updated_at TEXT COLLATE "C" NOT NULL
);

CREATE TABLE account_blocks (
  blocker_account_id TEXT COLLATE "C" NOT NULL REFERENCES real_accounts(id) ON DELETE CASCADE DEFERRABLE,
  blocked_account_id TEXT COLLATE "C" NOT NULL REFERENCES real_accounts(id) ON DELETE CASCADE DEFERRABLE,
  created_at TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY (blocker_account_id, blocked_account_id),
  CHECK (blocker_account_id <> blocked_account_id)
);

CREATE TABLE profiles (
  id TEXT COLLATE "C" PRIMARY KEY,
  display_name TEXT COLLATE "C" NOT NULL,
  avatar_label TEXT COLLATE "C" NOT NULL,
  is_synthetic BIGINT NOT NULL DEFAULT 1 CHECK (is_synthetic IN (0, 1))
);

CREATE TABLE audit_events (
  id TEXT COLLATE "C" PRIMARY KEY,
  event_type TEXT COLLATE "C" NOT NULL CHECK ( event_type IN ( 'session.created', 'session.validated', 'session.rejected', 'session.expired', 'session.invalidated', 'job.started', 'job.completed', 'job.failed', 'media.integrity_failed', 'media.consistency_quarantined', 'media.consistency_repaired', 'media.consistency_repair_failed' ) ),
  actor_member_id TEXT COLLATE "C" REFERENCES profiles(id) ON DELETE SET NULL DEFERRABLE,
  resource_id TEXT COLLATE "C",
  occurred_at TEXT COLLATE "C" NOT NULL,
  result TEXT COLLATE "C" NOT NULL CHECK (result IN ('success', 'failure', 'denied'))
);

CREATE TABLE auth_login_throttles (
  scope TEXT COLLATE "C" NOT NULL CHECK (scope IN ('account', 'source')),
  subject_hash TEXT COLLATE "C" NOT NULL,
  failures BIGINT NOT NULL CHECK (failures >= 0),
  window_started_at TEXT COLLATE "C" NOT NULL,
  cooldown_until TEXT COLLATE "C",
  cooldown_level BIGINT NOT NULL DEFAULT 0 CHECK (cooldown_level >= 0),
  updated_at TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY (scope, subject_hash)
);

CREATE TABLE groups (
  id TEXT COLLATE "C" PRIMARY KEY,
  name TEXT COLLATE "C" NOT NULL,
  current_cycle_id TEXT COLLATE "C"
);

CREATE TABLE cycles (
  id TEXT COLLATE "C" PRIMARY KEY,
  group_id TEXT COLLATE "C" NOT NULL REFERENCES groups(id) ON DELETE CASCADE DEFERRABLE,
  prompt TEXT COLLATE "C" NOT NULL,
  starts_at TEXT COLLATE "C" NOT NULL,
  ends_at TEXT COLLATE "C" NOT NULL,
  status TEXT COLLATE "C" NOT NULL,
  lock_state TEXT COLLATE "C" NOT NULL,
  max_count BIGINT NOT NULL,
  max_seconds BIGINT NOT NULL,
  count_used BIGINT NOT NULL DEFAULT 0,
  seconds_used DOUBLE PRECISION NOT NULL DEFAULT 0,
  release_status TEXT COLLATE "C" NOT NULL DEFAULT 'unpublished' CHECK (release_status IN ('unpublished', 'published')),
  release_published_at TEXT COLLATE "C",
  previous_cycle_id TEXT COLLATE "C" REFERENCES cycles(id) ON DELETE SET NULL DEFERRABLE
);

CREATE TABLE contributions (
  id TEXT COLLATE "C" PRIMARY KEY,
  cycle_id TEXT COLLATE "C" NOT NULL REFERENCES cycles(id) ON DELETE CASCADE DEFERRABLE,
  member_id TEXT COLLATE "C" NOT NULL REFERENCES profiles(id) ON DELETE CASCADE DEFERRABLE,
  media_job_id TEXT COLLATE "C",
  duration_seconds DOUBLE PRECISION NOT NULL,
  created_at TEXT COLLATE "C" NOT NULL,
  quota_window_start_at TEXT COLLATE "C",
  deleted_at TEXT COLLATE "C",
  replaced_by_contribution_id TEXT COLLATE "C" REFERENCES contributions(id) ON DELETE SET NULL DEFERRABLE,
  removed_at TEXT COLLATE "C",
  removed_by_account_id TEXT COLLATE "C" REFERENCES real_accounts(id) ON DELETE SET NULL DEFERRABLE
);

CREATE TABLE media_jobs (
  id TEXT COLLATE "C" PRIMARY KEY,
  group_id TEXT COLLATE "C" NOT NULL REFERENCES groups(id) ON DELETE CASCADE DEFERRABLE,
  contribution_id TEXT COLLATE "C" REFERENCES contributions(id) ON DELETE SET NULL DEFERRABLE,
  kind TEXT COLLATE "C" NOT NULL CHECK (kind IN ('clip', 'film', 'download')),
  status TEXT COLLATE "C" NOT NULL,
  output_path TEXT COLLATE "C",
  created_at TEXT COLLATE "C" NOT NULL,
  idempotency_key TEXT COLLATE "C",
  source_path TEXT COLLATE "C",
  trim_start_seconds DOUBLE PRECISION,
  trim_end_seconds DOUBLE PRECISION,
  mode TEXT COLLATE "C",
  error_code TEXT COLLATE "C",
  processing_started_at TEXT COLLATE "C",
  source_uri TEXT COLLATE "C",
  source_generation BIGINT,
  cycle_id TEXT COLLATE "C" REFERENCES cycles(id) ON DELETE CASCADE DEFERRABLE,
  progress BIGINT NOT NULL DEFAULT 0 CHECK (progress >= 0 AND progress <= 100),
  input_count BIGINT NOT NULL DEFAULT 0 CHECK (input_count >= 0),
  completed_count BIGINT NOT NULL DEFAULT 0 CHECK (completed_count >= 0),
  claim_generation BIGINT NOT NULL DEFAULT 0 CHECK (claim_generation >= 0),
  deleted_at TEXT COLLATE "C",
  attempt_count BIGINT NOT NULL DEFAULT 0 CHECK (attempt_count >= 0),
  updated_at TEXT COLLATE "C",
  failed_at TEXT COLLATE "C",
  output_sha256 TEXT COLLATE "C",
  output_bytes BIGINT CHECK (output_bytes IS NULL OR output_bytes > 0),
  output_verified_at TEXT COLLATE "C",
  media_type TEXT COLLATE "C" NOT NULL DEFAULT 'video' CHECK (media_type IN ('video', 'photo'))
);

CREATE TABLE compilation_job_inputs (
  job_id TEXT COLLATE "C" NOT NULL REFERENCES media_jobs(id) ON DELETE CASCADE DEFERRABLE,
  clip_job_id TEXT COLLATE "C" NOT NULL REFERENCES media_jobs(id) ON DELETE CASCADE DEFERRABLE,
  contribution_id TEXT COLLATE "C" NOT NULL REFERENCES contributions(id) ON DELETE CASCADE DEFERRABLE,
  position BIGINT NOT NULL CHECK (position >= 0),
  PRIMARY KEY (job_id, clip_job_id),
  UNIQUE (job_id, contribution_id)
);

CREATE TABLE messages (
  id TEXT COLLATE "C" PRIMARY KEY,
  group_id TEXT COLLATE "C" NOT NULL REFERENCES groups(id) ON DELETE CASCADE DEFERRABLE,
  member_id TEXT COLLATE "C" NOT NULL REFERENCES profiles(id) ON DELETE CASCADE DEFERRABLE,
  body TEXT COLLATE "C" NOT NULL,
  created_at TEXT COLLATE "C" NOT NULL,
  reply_to_message_id TEXT COLLATE "C" REFERENCES messages(id) ON DELETE SET NULL DEFERRABLE
);

CREATE TABLE content_reports (
  id TEXT COLLATE "C" PRIMARY KEY,
  reporter_account_id TEXT COLLATE "C" NOT NULL REFERENCES real_accounts(id) ON DELETE CASCADE DEFERRABLE,
  group_id TEXT COLLATE "C" REFERENCES groups(id) ON DELETE SET NULL DEFERRABLE,
  message_id TEXT COLLATE "C" REFERENCES messages(id) ON DELETE SET NULL DEFERRABLE,
  contribution_id TEXT COLLATE "C" REFERENCES contributions(id) ON DELETE SET NULL DEFERRABLE,
  reason TEXT COLLATE "C" NOT NULL DEFAULT '' CHECK (length(reason) <= 500),
  created_at TEXT COLLATE "C" NOT NULL,
  CHECK (message_id IS NULL OR contribution_id IS NULL),
  UNIQUE (reporter_account_id, message_id),
  UNIQUE (reporter_account_id, contribution_id)
);

CREATE TABLE contribution_quota_windows (
  id TEXT COLLATE "C" PRIMARY KEY,
  cycle_id TEXT COLLATE "C" NOT NULL REFERENCES cycles(id) ON DELETE CASCADE DEFERRABLE,
  member_id TEXT COLLATE "C" NOT NULL REFERENCES profiles(id) ON DELETE CASCADE DEFERRABLE,
  window_start_at TEXT COLLATE "C" NOT NULL,
  window_end_at TEXT COLLATE "C" NOT NULL,
  max_count BIGINT NOT NULL CHECK (max_count > 0 AND max_count <= 5),
  max_seconds BIGINT NOT NULL CHECK (max_seconds > 0 AND max_seconds <= 30),
  count_used BIGINT NOT NULL DEFAULT 0 CHECK (count_used >= 0),
  seconds_used DOUBLE PRECISION NOT NULL DEFAULT 0 CHECK (seconds_used >= 0),
  deletions_used BIGINT NOT NULL DEFAULT 0 CHECK (deletions_used >= 0 AND deletions_used <= 1),
  UNIQUE (cycle_id, member_id, window_start_at)
);

CREATE TABLE cycle_control_events (
  id TEXT COLLATE "C" PRIMARY KEY,
  cycle_id TEXT COLLATE "C" NOT NULL REFERENCES cycles(id) ON DELETE CASCADE DEFERRABLE,
  group_id TEXT COLLATE "C" NOT NULL REFERENCES groups(id) ON DELETE CASCADE DEFERRABLE,
  actor_member_id TEXT COLLATE "C" NOT NULL REFERENCES profiles(id) ON DELETE CASCADE DEFERRABLE,
  advance_seconds BIGINT NOT NULL CHECK (advance_seconds > 0),
  previous_starts_at TEXT COLLATE "C" NOT NULL,
  previous_ends_at TEXT COLLATE "C" NOT NULL,
  next_starts_at TEXT COLLATE "C" NOT NULL,
  next_ends_at TEXT COLLATE "C" NOT NULL,
  occurred_at TEXT COLLATE "C" NOT NULL
);

CREATE TABLE cycle_lifecycle_events (
  id TEXT COLLATE "C" PRIMARY KEY,
  cycle_id TEXT COLLATE "C" NOT NULL REFERENCES cycles(id) ON DELETE CASCADE DEFERRABLE,
  group_id TEXT COLLATE "C" NOT NULL REFERENCES groups(id) ON DELETE CASCADE DEFERRABLE,
  transition TEXT COLLATE "C" NOT NULL CHECK ( transition IN ('collecting_to_revealing', 'revealing_to_archived', 'next_cycle_created') ),
  occurred_at TEXT COLLATE "C" NOT NULL,
  UNIQUE (cycle_id, transition)
);

CREATE TABLE film_segments (
  film_job_id TEXT COLLATE "C" NOT NULL REFERENCES media_jobs(id) ON DELETE CASCADE DEFERRABLE,
  position BIGINT NOT NULL CHECK (position >= 0),
  contribution_id TEXT COLLATE "C" REFERENCES contributions(id) ON DELETE SET NULL DEFERRABLE,
  start_seconds DOUBLE PRECISION NOT NULL,
  duration_seconds DOUBLE PRECISION NOT NULL,
  PRIMARY KEY (film_job_id, position)
);

CREATE TABLE invites (
  id TEXT COLLATE "C" PRIMARY KEY,
  group_id TEXT COLLATE "C" NOT NULL REFERENCES groups(id) ON DELETE CASCADE DEFERRABLE,
  invitee_member_id TEXT COLLATE "C" REFERENCES profiles(id) ON DELETE SET NULL DEFERRABLE,
  status TEXT COLLATE "C" NOT NULL,
  created_at TEXT COLLATE "C" NOT NULL,
  code TEXT COLLATE "C",
  expires_at TEXT COLLATE "C",
  used_at TEXT COLLATE "C"
);

CREATE TABLE media_metadata (
  source_uri TEXT COLLATE "C" PRIMARY KEY,
  mime_type TEXT COLLATE "C" NOT NULL,
  byte_length BIGINT NOT NULL CHECK (byte_length > 0),
  duration_seconds DOUBLE PRECISION NOT NULL CHECK (duration_seconds > 0 AND duration_seconds <= 15),
  width BIGINT NOT NULL CHECK (width > 0),
  height BIGINT NOT NULL CHECK (height > 0),
  has_audio BIGINT NOT NULL CHECK (has_audio = 1),
  verified_at TEXT COLLATE "C" NOT NULL,
  media_type TEXT COLLATE "C" NOT NULL DEFAULT 'video' CHECK (media_type IN ('video', 'photo'))
);

CREATE TABLE member_reports (
  id TEXT COLLATE "C" PRIMARY KEY,
  reporter_account_id TEXT COLLATE "C" NOT NULL REFERENCES real_accounts(id) ON DELETE CASCADE DEFERRABLE,
  group_id TEXT COLLATE "C" REFERENCES groups(id) ON DELETE SET NULL DEFERRABLE,
  reported_account_id TEXT COLLATE "C" REFERENCES real_accounts(id) ON DELETE SET NULL DEFERRABLE,
  reason TEXT COLLATE "C" NOT NULL DEFAULT '' CHECK (length(reason) <= 500),
  created_at TEXT COLLATE "C" NOT NULL,
  CHECK (reporter_account_id <> reported_account_id),
  UNIQUE (reporter_account_id, group_id, reported_account_id)
);

CREATE TABLE memberships (
  group_id TEXT COLLATE "C" NOT NULL REFERENCES groups(id) ON DELETE CASCADE DEFERRABLE,
  member_id TEXT COLLATE "C" NOT NULL REFERENCES profiles(id) ON DELETE CASCADE DEFERRABLE,
  role TEXT COLLATE "C" NOT NULL DEFAULT 'member',
  accepted_at TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY (group_id, member_id)
);

CREATE TABLE reactions (
  id TEXT COLLATE "C" PRIMARY KEY,
  message_id TEXT COLLATE "C" NOT NULL REFERENCES messages(id) ON DELETE CASCADE DEFERRABLE,
  member_id TEXT COLLATE "C" NOT NULL REFERENCES profiles(id) ON DELETE CASCADE DEFERRABLE,
  emoji TEXT COLLATE "C" NOT NULL,
  created_at TEXT COLLATE "C" NOT NULL,
  UNIQUE (message_id, member_id, emoji)
);

CREATE TABLE real_group_metadata (
  group_id TEXT COLLATE "C" PRIMARY KEY REFERENCES groups(id) ON DELETE CASCADE DEFERRABLE,
  owner_account_id TEXT COLLATE "C" NOT NULL REFERENCES real_accounts(id) DEFERRABLE,
  max_members BIGINT NOT NULL CHECK (max_members BETWEEN 2 AND 10),
  cycle_duration_ms BIGINT NOT NULL CHECK (cycle_duration_ms = 2419200000),
  created_at TEXT COLLATE "C" NOT NULL,
  time_zone TEXT COLLATE "C" NOT NULL DEFAULT 'UTC'
);

CREATE TABLE real_profiles (
  id TEXT COLLATE "C" PRIMARY KEY,
  account_id TEXT COLLATE "C" NOT NULL UNIQUE REFERENCES real_accounts(id) ON DELETE CASCADE DEFERRABLE,
  display_name TEXT COLLATE "C" NOT NULL,
  created_at TEXT COLLATE "C" NOT NULL,
  UNIQUE (account_id, id)
);

CREATE TABLE real_group_memberships (
  group_id TEXT COLLATE "C" NOT NULL REFERENCES real_group_metadata(group_id) ON DELETE CASCADE DEFERRABLE,
  account_id TEXT COLLATE "C" NOT NULL,
  profile_id TEXT COLLATE "C" NOT NULL,
  role TEXT COLLATE "C" NOT NULL CHECK (role IN ('owner', 'member')),
  accepted_at TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY (group_id, account_id),
  FOREIGN KEY (account_id, profile_id) REFERENCES real_profiles(account_id, id) ON DELETE CASCADE DEFERRABLE
);

CREATE TABLE real_account_group_selections (
  account_id TEXT COLLATE "C" PRIMARY KEY REFERENCES real_accounts(id) ON DELETE CASCADE DEFERRABLE,
  group_id TEXT COLLATE "C" NOT NULL,
  FOREIGN KEY (group_id, account_id) REFERENCES real_group_memberships(group_id, account_id) ON DELETE CASCADE DEFERRABLE
);

CREATE TABLE real_account_sessions (
  token_hash TEXT COLLATE "C" PRIMARY KEY,
  account_id TEXT COLLATE "C" NOT NULL REFERENCES real_accounts(id) ON DELETE CASCADE DEFERRABLE,
  created_at TEXT COLLATE "C" NOT NULL,
  last_seen_at TEXT COLLATE "C" NOT NULL,
  idle_expires_at TEXT COLLATE "C" NOT NULL,
  absolute_expires_at TEXT COLLATE "C" NOT NULL,
  revoked_at TEXT COLLATE "C"
);

CREATE TABLE real_group_invites (
  id TEXT COLLATE "C" PRIMARY KEY,
  group_id TEXT COLLATE "C" NOT NULL REFERENCES real_group_metadata(group_id) ON DELETE CASCADE DEFERRABLE,
  owner_account_id TEXT COLLATE "C" NOT NULL REFERENCES real_accounts(id) ON DELETE CASCADE DEFERRABLE,
  code TEXT COLLATE "C" NOT NULL UNIQUE,
  created_at TEXT COLLATE "C" NOT NULL,
  expires_at TEXT COLLATE "C" NOT NULL,
  status TEXT COLLATE "C" NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'accepted', 'expired')),
  accepted_by_account_id TEXT COLLATE "C" REFERENCES real_accounts(id) DEFERRABLE,
  accepted_at TEXT COLLATE "C",
  CHECK (expires_at > created_at)
);

CREATE TABLE real_group_reminder_preferences (
  group_id TEXT COLLATE "C" NOT NULL,
  account_id TEXT COLLATE "C" NOT NULL,
  enabled BIGINT NOT NULL DEFAULT 0 CHECK (enabled IN (0, 1)),
  snoozed_until TEXT COLLATE "C",
  updated_at TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY (group_id, account_id),
  FOREIGN KEY (group_id, account_id) REFERENCES real_group_memberships(group_id, account_id) ON DELETE CASCADE DEFERRABLE
);

CREATE TABLE real_invite_guess_throttles (
  scope TEXT COLLATE "C" NOT NULL CHECK (scope IN ('account', 'source')),
  subject_hash TEXT COLLATE "C" NOT NULL,
  attempts BIGINT NOT NULL CHECK (attempts >= 0),
  window_started_at TEXT COLLATE "C" NOT NULL,
  updated_at TEXT COLLATE "C" NOT NULL,
  PRIMARY KEY (scope, subject_hash)
);

CREATE TABLE realtime_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  group_id TEXT COLLATE "C" NOT NULL REFERENCES groups(id) ON DELETE CASCADE DEFERRABLE,
  message_id TEXT COLLATE "C" NOT NULL UNIQUE REFERENCES messages(id) ON DELETE CASCADE DEFERRABLE,
  event_type TEXT COLLATE "C" NOT NULL CHECK (event_type = 'message'),
  occurred_at TEXT COLLATE "C" NOT NULL
);

CREATE TABLE reminder_destinations (
  id TEXT COLLATE "C" PRIMARY KEY,
  account_id TEXT COLLATE "C" NOT NULL REFERENCES real_accounts(id) ON DELETE CASCADE DEFERRABLE,
  session_token_hash TEXT COLLATE "C" NOT NULL REFERENCES real_account_sessions(token_hash) ON DELETE CASCADE DEFERRABLE,
  device_key TEXT COLLATE "C" NOT NULL,
  provider TEXT COLLATE "C" NOT NULL CHECK(provider IN ('expo','webpush')),
  destination_hash TEXT COLLATE "C" NOT NULL,
  destination_json TEXT COLLATE "C" NOT NULL,
  generation BIGINT NOT NULL DEFAULT 1 CHECK(generation > 0),
  enabled BIGINT NOT NULL CHECK(enabled IN (0,1)),
  created_at TEXT COLLATE "C" NOT NULL,
  updated_at TEXT COLLATE "C" NOT NULL,
  UNIQUE(account_id,device_key),
  UNIQUE(provider,destination_hash)
);

CREATE TABLE reminder_outbox (
  id TEXT COLLATE "C" PRIMARY KEY,
  group_id TEXT COLLATE "C" NOT NULL,
  account_id TEXT COLLATE "C" NOT NULL,
  local_sunday TEXT COLLATE "C" NOT NULL,
  scheduled_at TEXT COLLATE "C" NOT NULL,
  destination_id TEXT COLLATE "C" REFERENCES reminder_destinations(id) ON DELETE SET NULL DEFERRABLE,
  destination_generation BIGINT NOT NULL CHECK(destination_generation > 0),
  state TEXT COLLATE "C" NOT NULL CHECK(state IN ('pending','sending','retry','awaiting_receipt','accepted','failed','cancelled')),
  attempts BIGINT NOT NULL DEFAULT 0 CHECK(attempts BETWEEN 0 AND 3),
  receipt_attempts BIGINT NOT NULL DEFAULT 0 CHECK(receipt_attempts BETWEEN 0 AND 3),
  provider_receipt TEXT COLLATE "C",
  response_category TEXT COLLATE "C",
  next_attempt_at TEXT COLLATE "C" NOT NULL,
  lease_id TEXT COLLATE "C",
  lease_expires_at TEXT COLLATE "C",
  created_at TEXT COLLATE "C" NOT NULL,
  updated_at TEXT COLLATE "C" NOT NULL,
  UNIQUE(group_id,account_id,local_sunday),
  FOREIGN KEY(group_id,account_id) REFERENCES real_group_memberships(group_id,account_id) ON DELETE CASCADE DEFERRABLE,
  CHECK((lease_id IS NULL) = (lease_expires_at IS NULL))
);

CREATE TABLE sessions (
  id TEXT COLLATE "C" PRIMARY KEY,
  member_id TEXT COLLATE "C" NOT NULL REFERENCES profiles(id) ON DELETE CASCADE DEFERRABLE,
  group_id TEXT COLLATE "C" NOT NULL REFERENCES groups(id) ON DELETE CASCADE DEFERRABLE,
  started_at TEXT COLLATE "C" NOT NULL,
  last_seen_at TEXT COLLATE "C" NOT NULL,
  access_kind TEXT COLLATE "C" NOT NULL DEFAULT 'demo' CHECK (access_kind = 'demo'),
  expires_at TEXT COLLATE "C" NOT NULL DEFAULT '1970-01-01T00:00:00.000Z',
  invalidated_at TEXT COLLATE "C"
);

CREATE TABLE staged_sources (
  source_id TEXT COLLATE "C" PRIMARY KEY,
  source_uri TEXT COLLATE "C" NOT NULL UNIQUE,
  idempotency_key_hash TEXT COLLATE "C" NOT NULL UNIQUE,
  group_id TEXT COLLATE "C" NOT NULL REFERENCES groups(id) ON DELETE CASCADE DEFERRABLE,
  member_id TEXT COLLATE "C" NOT NULL REFERENCES profiles(id) ON DELETE CASCADE DEFERRABLE,
  source_path TEXT COLLATE "C",
  byte_length BIGINT CHECK (byte_length IS NULL OR byte_length > 0),
  status TEXT COLLATE "C" NOT NULL CHECK (status IN ('pending', 'staged')),
  created_at TEXT COLLATE "C" NOT NULL,
  claim_generation BIGINT NOT NULL DEFAULT 0 CHECK (claim_generation >= 0),
  claim_expires_at TEXT COLLATE "C"
);

CREATE TABLE upload_intents (
  id TEXT COLLATE "C" PRIMARY KEY,
  environment TEXT COLLATE "C" NOT NULL,
  group_id TEXT COLLATE "C" NOT NULL REFERENCES real_group_metadata(group_id) DEFERRABLE,
  account_id TEXT COLLATE "C" NOT NULL REFERENCES real_accounts(id) DEFERRABLE,
  profile_id TEXT COLLATE "C" NOT NULL REFERENCES real_profiles(id) DEFERRABLE,
  cycle_id TEXT COLLATE "C" NOT NULL REFERENCES cycles(id) DEFERRABLE,
  quota_window_start_at TEXT COLLATE "C" NOT NULL,
  idempotency_hash TEXT COLLATE "C" NOT NULL,
  request_hash TEXT COLLATE "C" NOT NULL,
  request_json TEXT COLLATE "C" NOT NULL,
  target_json TEXT COLLATE "C" NOT NULL,
  reserved_seconds DOUBLE PRECISION NOT NULL CHECK (reserved_seconds > 0 AND reserved_seconds <= 15),
  state TEXT COLLATE "C" NOT NULL CHECK (state IN ('open','pinned','completed','expired')),
  pinned_ref TEXT COLLATE "C",
  contribution_id TEXT COLLATE "C" UNIQUE REFERENCES contributions(id) DEFERRABLE,
  job_id TEXT COLLATE "C" UNIQUE REFERENCES media_jobs(id) DEFERRABLE,
  created_at TEXT COLLATE "C" NOT NULL,
  expires_at TEXT COLLATE "C" NOT NULL,
  updated_at TEXT COLLATE "C" NOT NULL,
  cleanup_cursor TEXT COLLATE "C",
  cleanup_complete BIGINT NOT NULL DEFAULT 0 CHECK (cleanup_complete IN (0,1)),
  UNIQUE (environment, group_id, profile_id, idempotency_hash),
  CHECK ((state = 'open' AND pinned_ref IS NULL) OR state = 'expired' OR (state IN ('pinned','completed') AND pinned_ref IS NOT NULL)),
  CHECK ((state = 'completed' AND contribution_id IS NOT NULL AND job_id IS NOT NULL) OR (state <> 'completed' AND contribution_id IS NULL AND job_id IS NULL))
);

CREATE INDEX account_blocks_blocked_account_idx ON account_blocks (blocked_account_id);

CREATE INDEX audit_events_occurred_at_idx ON audit_events (occurred_at DESC, id DESC);

CREATE INDEX audit_events_resource_id_idx ON audit_events (resource_id);

CREATE INDEX "compilation_job_inputs_order_idx" ON "compilation_job_inputs" (job_id, position);

CREATE INDEX content_reports_contribution_idx ON content_reports (contribution_id);

CREATE INDEX content_reports_created_idx ON content_reports (created_at);

CREATE INDEX content_reports_group_idx ON content_reports (group_id);

CREATE INDEX content_reports_message_idx ON content_reports (message_id);

CREATE INDEX contribution_quota_windows_member_idx ON contribution_quota_windows (cycle_id, member_id, window_start_at);

CREATE INDEX contributions_active_cycle_idx ON contributions (cycle_id, member_id, deleted_at, created_at);

CREATE INDEX contributions_ledger_member_idx ON contributions (cycle_id, member_id, created_at, id);

CREATE INDEX contributions_removed_by_account_idx ON contributions (removed_by_account_id);

CREATE INDEX cycle_control_events_cycle_idx ON cycle_control_events (cycle_id, occurred_at DESC, id DESC);

CREATE INDEX cycle_lifecycle_events_group_idx ON cycle_lifecycle_events (group_id, occurred_at, id);

CREATE UNIQUE INDEX cycle_lifecycle_events_receipt_idx ON cycle_lifecycle_events (cycle_id, transition);

CREATE UNIQUE INDEX cycles_previous_cycle_idx ON cycles (previous_cycle_id) WHERE previous_cycle_id IS NOT NULL;

CREATE INDEX film_segments_contribution_idx ON film_segments (contribution_id);

CREATE UNIQUE INDEX invites_code_idx ON invites (code) WHERE code IS NOT NULL;

CREATE INDEX "media_jobs_cycle_idx" ON "media_jobs" (cycle_id, kind, created_at);

CREATE UNIQUE INDEX media_jobs_idempotency_idx ON media_jobs (idempotency_key) WHERE idempotency_key IS NOT NULL;

CREATE UNIQUE INDEX "media_jobs_one_film_per_cycle_idx" ON "media_jobs" (cycle_id) WHERE kind = 'film' AND cycle_id IS NOT NULL;

CREATE INDEX "media_jobs_queue_group_idx" ON media_jobs (group_id, created_at, id);

CREATE INDEX "media_jobs_queue_group_kind_idx" ON media_jobs (group_id, kind, created_at, id);

CREATE INDEX "media_jobs_queue_group_kind_status_idx" ON media_jobs (group_id, kind, status, created_at, id);

CREATE INDEX "media_jobs_queue_group_status_idx" ON media_jobs (group_id, status, created_at, id);

CREATE INDEX media_jobs_source_binding_idx ON media_jobs (source_uri, source_generation, source_path);

CREATE INDEX member_reports_created_idx ON member_reports (created_at);

CREATE INDEX member_reports_group_idx ON member_reports (group_id);

CREATE INDEX member_reports_reported_account_idx ON member_reports (reported_account_id);

CREATE INDEX messages_reply_to_idx ON messages (reply_to_message_id);

CREATE INDEX real_account_sessions_account_idx ON real_account_sessions (account_id, revoked_at);

CREATE INDEX real_group_invites_group_created_idx ON real_group_invites (group_id, created_at);

CREATE INDEX real_group_invites_status_expiry_idx ON real_group_invites (status, expires_at);

CREATE INDEX real_group_memberships_account_idx ON real_group_memberships (account_id, accepted_at);

CREATE INDEX real_invite_guess_throttles_window_idx ON real_invite_guess_throttles (window_started_at);

CREATE INDEX realtime_events_group_idx ON realtime_events (group_id, id);

CREATE INDEX reminder_destinations_account_idx ON reminder_destinations(account_id,enabled,updated_at);

CREATE INDEX reminder_outbox_due_idx ON reminder_outbox(state,next_attempt_at,id);

CREATE INDEX staged_sources_owner_idx ON staged_sources (group_id, member_id, created_at DESC);

CREATE INDEX upload_intents_expiry_idx ON upload_intents(environment, cleanup_complete, expires_at, id);

CREATE INDEX upload_intents_quota_idx ON upload_intents(cycle_id, profile_id, quota_window_start_at, state, expires_at);


-- SQLite's julianday() for ISO-8601 text, used by operational metrics.
CREATE FUNCTION julianday(value TEXT) RETURNS DOUBLE PRECISION
LANGUAGE sql STABLE AS $$
  SELECT EXTRACT(EPOCH FROM value::timestamptz) / 86400.0 + 2440587.5
$$;

-- Real profiles mirror into the media actor table (SQLite migration 022).
CREATE FUNCTION real_profile_media_actor_insert() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  INSERT INTO profiles (id, display_name, avatar_label, is_synthetic)
  VALUES (NEW.id, NEW.display_name, 'REAL ACCOUNT', 0)
  ON CONFLICT DO NOTHING;
  RETURN NULL;
END;
$$;

CREATE TRIGGER real_profile_media_actor_insert
AFTER INSERT ON real_profiles
FOR EACH ROW EXECUTE FUNCTION real_profile_media_actor_insert();

CREATE FUNCTION real_profile_media_actor_update() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  UPDATE profiles SET display_name = NEW.display_name
  WHERE id = NEW.id AND is_synthetic = 0;
  RETURN NULL;
END;
$$;

CREATE TRIGGER real_profile_media_actor_update
AFTER UPDATE OF display_name ON real_profiles
FOR EACH ROW EXECUTE FUNCTION real_profile_media_actor_update();

CREATE FUNCTION real_profile_media_actor_delete() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  DELETE FROM profiles WHERE id = OLD.id AND is_synthetic = 0;
  RETURN NULL;
END;
$$;

CREATE TRIGGER real_profile_media_actor_delete
AFTER DELETE ON real_profiles
FOR EACH ROW EXECUTE FUNCTION real_profile_media_actor_delete();

-- This baseline stands in for SQLite migrations 1-30.
INSERT INTO schema_migrations (version, applied_at)
SELECT version, to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')
FROM generate_series(1, 30) AS version;

INSERT INTO schema_migration_markers (migration_key, applied_at)
SELECT migration_key, to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')
FROM unnest(ARRAY[
  'initial-v1',
  'session-audit-v1',
  'cycle-controls-v1',
  'invites-v1',
  'media-idempotency-v1',
  'contribution-quota-v1',
  'media-processing-v1',
  'media-source-binding-v1',
  'cycle-lifecycle-v1',
  'contribution-deletion-v1',
  'realtime-messages-v1',
  'chat-replies-reactions-v1',
  'compilation-retry-v1',
  'queue-observability-v1',
  'media-integrity-v1',
  'contribution-ledger-v1',
  'consistency-repair-audit-v1',
  'real-account-auth-v1',
  'real-groups-v1',
  'real-group-invites-v1',
  'real-group-invite-acceptance-v1',
  'real-media-profile-bridge-v1',
  'photo-media-v1',
  'real-invite-guess-throttles-v1',
  'real-group-reminders-v1',
  'upload-intents-v1',
  'reminder-outbox-v1',
  'content-safety-v1',
  'member-reports-v1',
  'moderation-records-v1'
]) AS migration_key;
